import { eq } from "drizzle-orm";

import { db } from "../db/index.js";

import { lessonContents } from "../db/schema/lessonContents.js";
import { lessons } from "../db/schema/lesson.js";

import { buildLessonPrompt } from "../prompts/lesson.prompt.js";

import { generateRoadmap } from "./ai.service.js";


export async function getLessonContent(lessonId) {

  // Step 1: Check if content already exists
  const [existingContent] = await db
    .select()
    .from(lessonContents)
    .where(eq(lessonContents.lessonId, lessonId));

  if (existingContent) {
    return existingContent;
  }

  // Step 2: Get lesson information
  const [lesson] = await db
    .select()
    .from(lessons)
    .where(eq(lessons.id, lessonId));

  if (!lesson) {
    throw new Error("Lesson not found");
  }

  // Step 3: Build AI prompt
  const prompt = buildLessonPrompt(lesson);

  // Step 4: Ask Gemini
  const result = await generateRoadmap(prompt);

  // Step 5: Clean AI response
  const cleanJson = result
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim();

  // Step 6: Parse JSON
  let data;

  try {
    data = JSON.parse(cleanJson);
  } catch (error) {
    console.log(cleanJson);

    throw new Error(
      "Invalid lesson content generated by AI"
    );
  }

  // ⬇️ We'll continue from here next...
  if (
  !data.notes ||
  !data.codeExample ||
  !data.exercise ||
  !data.summary
) {
  throw new Error(
    "AI returned incomplete lesson content"
  );


	}

	const [savedContent] = await db
  .insert(lessonContents)
  .values({

    lessonId,

    notes: data.notes,

    codeExample: data.codeExample,

    exercise: data.exercise,

    summary: data.summary,

  })
  .returning();

  return savedContent;
}
